apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment-devops
  namespace: httpd-namespace-devops
  labels: 
    app: httpd-app
spec:
  template:
    metadata:
      name: httpd-pod-devops
      labels:
        app: httpd-app
    spec:
      containers:
      - name: httpd-container-devops
        image: httpd:latest
        ports:
          - containerPort: 80

  replicas: 2
  selector:
    matchLabels:
      app: httpd-app
