apiVersion: v1
kind: Service
metadata:
  name: httpd-service-devops
  namespace: httpd-namespace-devops
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30004
  selector:
    app: httpd-app
