---
      apiVersion: v1
      kind: Service
      metadata:
       name: service-grafana
      spec:
       type: NodePort
       ports:
       - targetPort: 3000
         port: 3000
         nodePort: 32000
       selector:
         app: grafana

---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: grafana-deployment-xfusion
      labels:
        app: grafana
    spec:
     template:
        metadata:
          name: grafana-pod-xfusion
          labels:
            app: grafana
        spec:
         containers:
         - name: grafana-container-xfusion
           image: grafana/grafana:latest
           ports:
           - containerPort: 3000             
     replicas: 1
     selector:
       matchLabels:
        app: grafana
