apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy
  namespace: datacenter
  labels: 
    app: httpd-app
spec:
  template:
    metadata:
      name: httpd-pod
      labels:
        app: httpd-app
    spec:
      containers:
      - name: httpd
        image: httpd:2.4.28

  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2 
  selector:
    matchLabels:
      app: httpd-app
