 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: ic-deploy-devops
   labels: 
     app: ic-devops
 spec:
   template:
     metadata:
       name: ic-pod-devops
       labels:
         app: ic-devops
     spec:
       containers:
         - name: ic-main-devops
           image: fedora:latest
           command: ['/bin/bash', '-c', 'while true; do cat /ic/official; sleep 5; done']
           volumeMounts:
             - name: ic-volume-devops
               mountPath: /ic       
       initContainers:
         - name: ic-msg-devops
           image: fedora:latest
           command: ['/bin/bash', '-c', 'echo Init Done - Welcome to xFusionCorp Industries > /ic/official']
           volumeMounts:
             - name: ic-volume-devops
               mountPath: /ic
       volumes:
         - name: ic-volume-devops
           emptyDir: {}

   replicas: 1
   selector:
     matchLabels:
       app: ic-devops
