kubectl create secret generic mysql-root-pass --from-literal=password=YUIidhb667
kubectl create secret generic mysql-user-pass --from-literal=username=kodekloud_tim --from-literal=password=YchZHRcLkL
kubectl create secret generic mysql-db-url --from-literal=database=kodekloud_db10


---
#Persistent Volume definition

 apiVersion: v1 
 kind: PersistentVolume 
 metadata:
   name: mysql-pv
 spec:
   storageClassName: standard       
   capacity:
     storage: 250Mi
   accessModes: 
      -  ReadWriteOnce 
   hostPath:                       
     path: "/var/lib/mysql"
   persistentVolumeReclaimPolicy: Retain  

---
#Persistent Volume Claim Definition

 apiVersion: v1 
 kind: PersistentVolumeClaim       
 metadata:                          
   name: mysql-pv-claim
 spec:                               
   storageClassName: standard       
   accessModes: 
   - ReadWriteOnce             
   resources:
     requests:
       storage: 250Mi 

---
#NodePort Service definition

 apiVersion: v1                    
 kind: Service                      
 metadata:
   name: mysql         
   labels:             
     app: mysql-app  
 spec:
   type: NodePort
   ports:
     - targetPort: 3306
       port: 3306
       nodePort: 30007
   selector:                       
     app: mysql_app

---
#MySql Deployment Definition

 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: mysql-deployment
   labels:
     app: mysql-app
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: mysql-app
   template:
     metadata:
       labels:
         app: mysql-app
         tier: mysql
     spec:
       containers:
       - image: mysql:latest
         name: mysql
         env:
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
               name: mysql-root-pass
               key: password
         - name: MYSQL_DATABASE
           valueFrom:
             secretKeyRef:
               name: mysql-db-url
               key: database
         - name: MYSQL_USER
           valueFrom:
             secretKeyRef:
               name: mysql-user-pass
               key: username
         - name: MYSQL_PASSWORD
           valueFrom:
             secretKeyRef:
               name: mysql-user-pass
               key: password
         ports:
         - containerPort: 3306
           name: mysql
         volumeMounts:
         - name: mysql-pv
           mountPath: /var/lib/mysql
       volumes:
       - name: mysql-pv
         persistentVolumeClaim:
            claimName: mysql-pv-claim
