---
apiVersion: v1
kind: Namespace
metadata:
  name: node-namespace-nautilus

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-app
  name: node-service-nautilus
  namespace: node-namespace-nautilus
spec:
  ports:
  - name: 80-8080
    nodePort: 30012
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: node-app
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-app
  name: node-deployment-nautilus
  namespace: node-namespace-nautilus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node-app
    spec:
      containers:
      - image: gcr.io/kodekloud/centos-ssh-enabled:node
        name: centos-ssh-enabled
        ports:
        - containerPort: 80
