 apiVersion: apps/v1
 kind: ReplicaSet
 metadata:
   name: httpd-replicaset
   labels: 
     app: httpd_app
     type: front-end
 spec:
   template:
     metadata:
       labels:
         app: httpd_app
         type: front-eind
     spec:
       containers:
       - name: httpd-container
         image: httpd:latest

   replicas: 4
   selector:
     matchLabels:
       app: httpd_app
       type: front-end
