apiVersion: v1
kind: Pod
metadata:
  name: secret-devops
  labels: 
    app: secret_app
spec:
  containers:
    - name: secret-container-devops
      image: ubuntu:latest
      command: ['/bin/bash', '-c', 'sleep 10000']
      volumeMounts:
      - name: secret-volume-devops
        mountPath: /opt/demo
        readOnly: true
  volumes:
    - name: secret-volume-devops
      secret:
        secretName: news
        
