apiVersion: v1
kind: ConfigMap
metadata:
  name: time-config
  namespace: datacenter
data:
  TIME_FREQ: "11"

---
apiVersion: v1
kind: Pod
metadata:
  name: time-check
  namespace: datacenter
  labels: 
    app: time-check-app
spec:
  containers:
    - name: time-check
      image: busybox:latest
      envFrom:
        - configMapRef:
            name: time-config

      command: ['/bin/sh', '-c', 'while true; do date; sleep $TIME_FREQ;done > /opt/sysops/time/time-check.log']
      volumeMounts:
        - name: log-volume
          mountPath: /opt/sysops/time
  volumes:
    - name: log-volume
      emptyDir: {}
      
