apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment-xfusion
  namespace: tomcat-namespace-xfusion
  labels: 
    app: tomcat-app
spec:
  template:
    metadata:
      name: tomcat-pod-xfusion
      labels:
        app: tomcat-app
    spec:
      containers:
      - name: tomcat-container-xfusion
        image: gcr.io/kodekloud/centos-ssh-enabled:tomcat
        ports: 
          - containerPort: 8080

  replicas: 1
  selector:
    matchLabels:
      app: tomcat-app
