apiVersion: v1
kind: Service
metadata:
  name: tomcat-service-xfusion
  namespace: tomcat-namespace-xfusion
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 80
      nodePort: 32227
      protocol: TCP
  selector:
    app: tomcat-app
