---
- hosts: all
  become: yes
  tasks:
    - name: Create a zip archive
      archive:
        path: /usr/src/dba/
        dest: /opt/dba/beta.tar.gz
        format: gz
        force_archive: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

