---
- hosts: all
  become: yes
  tasks:
    - name: Create a file and configure file properties
      file:
        path: /usr/src/data.txt
        state: touch
        mode: '0644'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

